spring:
  data:
    redis:
      # 连接超时时间（毫秒）
      timeout: 300000
      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 20
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1

redisson:
  # 线程池数量
  threads: 16
  # Netty线程池数量
  nettyThreads: 32
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: ${spring.application.name}
    # 最小空闲连接数
    connectionMinimumIdleSize: 32
    # 连接池大小
    connectionPoolSize: 64
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 100000
    # 命令等待超时，单位：毫秒
    timeout: 1000000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50